#version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak-server
    command: ["start-dev"]
    environment:
      KC_DB: dev-file

      KC_HOSTNAME: localhost
      KC_HTTP_RELATIVE_PATH: /
      KC_LOG_LEVEL: INFO

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data:
